### ISSUE TITLE
New model (pre release 3.0.0) got so LAG compared to previous version (AIV-724)

### ISSUE THREAD

**Issue by nhattran02** [espressif/esp-dl#179]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Provided a clear description of your suggestion.
- [X] Included any relevant context or examples.

### Issue or Suggestion Description

New model (pre release 3.0.0) got so LAG compared to previous version

**Comment by sun-xiangyu** [comment]
Due to certain reasons, the development of ESP-DL was suspended for a period of time. As you can see, we have now completely refactored ESP-DL, rewritten almost all operators, and added support for the ESP32-P4 chip. For ESP-DL v3.0, we aim to ensure compatibility with all previous operators and ONNX.

If you have any requirements or suggestions for new esp-dl, please share your thoughts.
